name: Build

on:
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout this
        uses: actions/checkout@v4
        with:
          path: build
      - name: Export version to variable
        run: |
            export TM_SHA=$(cat build/sha)
            echo "TM_SHA=$TM_SHA" >> $GITHUB_ENV
        shell: bash
      - name: Checkout tm
        uses: actions/checkout@v4
        with:
          repository: terraforming-mars/terraforming-mars
          path: tm
          ref: ${{ env.TM_SHA }}
      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          push: true
          platforms: linux/amd64,linux/arm64
          context: tm
          tags: andrewsav/terraforming-mars
